import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { URL_MAP, toCleanUrl } from './scripts/url-map.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const DIST = path.join(__dirname, 'dist');
const BASE_URL = process.env.SITE_URL || 'https://OrianWave.one';

// ─────────────────────────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────────────────────────

function findHtmlFiles(dir) {
  const files = [];
  const items = fs.readdirSync(dir);
  for (const item of items) {
    const fullPath = path.join(dir, item);
    const stat = fs.statSync(fullPath);
    if (stat.isDirectory()) {
      files.push(...findHtmlFiles(fullPath));
    } else if (item.endsWith('.html')) {
      files.push(fullPath);
    }
  }
  return files;
}

// ─────────────────────────────────────────────────────────────────────────────
// Step 1: Fix JavaScript file naming (existing logic)
// ─────────────────────────────────────────────────────────────────────────────

function fixJavaScriptFile() {
  const assetsDir = path.join(DIST, 'assets');
  if (!fs.existsSync(assetsDir)) return;

  const files = fs.readdirSync(assetsDir);
  const jsFile = files.find((file) => file.startsWith('main') && file.endsWith('.js'));

  if (jsFile && jsFile !== 'main.js') {
    const oldPath = path.join(assetsDir, jsFile);
    const newPath = path.join(assetsDir, 'main.js');
    fs.renameSync(oldPath, newPath);
    console.log(`✅ Renamed ${jsFile} → main.js`);

    const htmlFiles = findHtmlFiles(DIST);
    htmlFiles.forEach((filePath) => {
      let content = fs.readFileSync(filePath, 'utf8');
      content = content.replace(new RegExp(jsFile, 'g'), 'main.js');
      if (content.includes('<!-- SCRIPT -->') && !content.includes('src="./assets/main.js"')) {
        content = content.replace('<!-- SCRIPT -->', '<script src="./assets/main.js"></script>');
      }
      if (!content.includes('href="./assets/main.css"')) {
        content = content.replace(
          /(<link\s+href="https:\/\/fonts\.googleapis\.com\/css2[^>]*>\s*)/,
          '$1<link rel="stylesheet" href="./assets/main.css" />\n'
        );
      }
      fs.writeFileSync(filePath, content, 'utf8');
    });
  } else {
    console.log('ℹ️  JS file already named main.js or not found.');
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// Step 2: Generate _redirects (Netlify / Replit static hosting)
// ─────────────────────────────────────────────────────────────────────────────

function generateRedirects() {
  const lines = [
    '# OrianWave URL Redirects — auto-generated by post-build.js',
    '# Format: <source>  <destination>  <status>',
    '',
    '# ── Remove .html extension ──────────────────────────────────────',
  ];

  const distHtmlFiles = fs.existsSync(DIST)
    ? fs.readdirSync(DIST).filter((f) => f.endsWith('.html'))
    : [];

  for (const file of distHtmlFiles) {
    const slug = file.replace('.html', '');
    lines.push(`/${slug}.html    /${slug}    301`);
  }

  lines.push('');
  lines.push('# ── Dirty → Clean URL redirects ─────────────────────────────────');

  for (const [slug, cleanPath] of Object.entries(URL_MAP)) {
    if (cleanPath === '/') {
      lines.push(`/${slug}    /    301`);
      lines.push(`/${slug}.html    /    301`);
    } else {
      lines.push(`/${slug}    ${cleanPath}    301`);
      lines.push(`/${slug}.html    ${cleanPath}    301`);
    }
  }

  lines.push('');
  lines.push('# ── SPA fallback ─────────────────────────────────────────────────');
  lines.push('/*    /digital-marketing.html    200');

  const redirectsPath = path.join(DIST, '_redirects');
  fs.writeFileSync(redirectsPath, lines.join('\n'), 'utf8');
  console.log(
    `✅ _redirects written → dist/_redirects (${Object.keys(URL_MAP).length * 2} redirect rules)`
  );
}

// ─────────────────────────────────────────────────────────────────────────────
// Step 3: Generate sitemap.xml in dist/
// ─────────────────────────────────────────────────────────────────────────────

function generateSitemap() {
  const today = new Date().toISOString().split('T')[0];

  // Priority mapping
  const priorityMap = {
    '/': '1.0',
    '/services': '0.9',
    '/contact': '0.9',
    '/pricing': '0.9',
    '/web-development': '0.85',
    '/custom-software': '0.85',
    '/seo-optimization': '0.85',
    '/ecommerce': '0.85',
    '/products': '0.85',

    '/case-studies': '0.7',
    '/success-stories': '0.7',
    '/faq': '0.65',
    '/about': '0.65',
    '/about/team': '0.6',
  };

  // Only include pages that exist in dist
  const distHtmlFiles = new Set(
    fs.existsSync(DIST)
      ? fs
          .readdirSync(DIST)
          .filter((f) => f.endsWith('.html'))
          .map((f) => f.replace('.html', ''))
      : []
  );

  const entries = [];

  for (const [slug, cleanPath] of Object.entries(URL_MAP)) {
    if (!distHtmlFiles.has(slug)) continue;

    const priority = priorityMap[cleanPath] || '0.6';
    const changefreq =
      priority >= '0.85' ? 'monthly' : cleanPath === '/blog' ? 'weekly' : 'monthly';
    const loc = BASE_URL + cleanPath;
    entries.push({ loc, priority, changefreq, lastmod: today });
  }

  // Sort: homepage first, then by priority
  entries.sort((a, b) => {
    if (a.loc === BASE_URL + '/') return -1;
    if (b.loc === BASE_URL + '/') return 1;
    return parseFloat(b.priority) - parseFloat(a.priority) || a.loc.localeCompare(b.loc);
  });

  const xml = [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"',
    '        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"',
    '        xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9',
    '          http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd">',
    '',
    ...entries.map(({ loc, priority, changefreq, lastmod }) =>
      [
        '  <url>',
        `    <loc>${loc}</loc>`,
        `    <lastmod>${lastmod}</lastmod>`,
        `    <changefreq>${changefreq}</changefreq>`,
        `    <priority>${priority}</priority>`,
        '  </url>',
      ].join('\n')
    ),
    '',
    '</urlset>',
  ].join('\n');

  fs.writeFileSync(path.join(DIST, 'sitemap.xml'), xml, 'utf8');
  console.log(`✅ sitemap.xml written → dist/sitemap.xml (${entries.length} URLs)`);
}

// ─────────────────────────────────────────────────────────────────────────────
// Step 4: Add <link rel="canonical"> to HTML files using clean URLs
// ─────────────────────────────────────────────────────────────────────────────

function injectCanonicals() {
  if (!fs.existsSync(DIST)) return;

  const htmlFiles = fs.readdirSync(DIST).filter((f) => f.endsWith('.html'));
  let count = 0;

  for (const file of htmlFiles) {
    const slug = file.replace('.html', '');
    const cleanPath = URL_MAP[slug] || '/' + toCleanUrl(slug).replace(/^\//, '');
    const canonicalUrl = BASE_URL + cleanPath;

    const filePath = path.join(DIST, file);
    let content = fs.readFileSync(filePath, 'utf8');

    // Skip if canonical already exists
    if (content.includes('<link rel="canonical"')) continue;

    // Inject before </head>
    const canonical = `  <link rel="canonical" href="${canonicalUrl}" />\n`;
    content = content.replace('</head>', canonical + '</head>');
    fs.writeFileSync(filePath, content, 'utf8');
    count++;
  }

  console.log(`✅ Canonical tags injected → ${count} HTML files`);
}

// ─────────────────────────────────────────────────────────────────────────────
// Run all steps
// ─────────────────────────────────────────────────────────────────────────────

console.log('\n🚀 Running OrianWave post-build pipeline...\n');

fixJavaScriptFile();
generateRedirects();
generateSitemap();
injectCanonicals();

console.log('\n✨ Post-build complete.\n');
